// QuestionBank: teacher's library of reusable exam questions (five types). Questions can be AI-generated, imported from approved study sets, filtered,
// tagged with a CLO, deleted, and (in `selectable` mode) used as a checkbox picker inside the exam builder.
import React, { useEffect, useMemo, useState } from 'react';
import {
  Library, Sparkles, RefreshCw, Trash2, Search, Filter, Download, AlertTriangle,
  CheckCircle2, ListChecks, ToggleLeft, Type, Shuffle, ChevronDown, ChevronUp,
} from 'lucide-react';
import { questionBankService, contentGenerationService, courseService, outcomesService } from '../services/api';
import type { BankQuestion, QuestionType, GeneratableConcept, GeneratedContentItem, CLO } from '../services/api';
import { EmptyStateIllustration } from './illustrations';
import { apiErrorMessage } from '../lib/apiError';

interface QuestionBankProps {
  courseId: number;
  /** Lets the exam builder embed the bank as a picker instead of a manager. */
  selectable?: boolean;
  selectedIds?: number[];
  onToggleSelect?: (id: number) => void;
}

// Icon shown for each question type.
const TYPE_ICONS: Record<QuestionType, React.ElementType> = {
  single_choice: ListChecks,
  multi_select: ListChecks,
  true_false: ToggleLeft,
  fill_blank: Type,
  matching: Shuffle,
};

// Difficulty levels offered for filtering/generation.
const DIFFICULTIES = ['Easy', 'Medium', 'Hard'] as const;
// Maps a difficulty name to its global CSS badge class.
const badgeClassFor = (d: string) => `badge-${(d || 'medium').toLowerCase()}`;

/**
 * The teacher's library of reusable exam questions.
 *
 * Distinct from generated study material: that is a whole set tied to one concept and
 * meant to be studied, whereas these are individual questions that get mixed across
 * concepts into an exam. Questions arrive three ways - generated by AI in any of the
 * five types, imported wholesale from an already-approved study set, or written by
 * hand - and every one is stored with a validated answer key.
 */
// Main component: loads questions, question types, concepts, generated sets and CLOs, and renders the filters, generator, importer and list.
export const QuestionBank: React.FC<QuestionBankProps> = ({
  courseId, selectable = false, selectedIds = [], onToggleSelect,
}) => {
  const [questions, setQuestions] = useState<BankQuestion[]>([]);
  const [types, setTypes] = useState<Array<{ key: QuestionType; label: string }>>([]);
  const [concepts, setConcepts] = useState<GeneratableConcept[]>([]);
  const [sets, setSets] = useState<GeneratedContentItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [expanded, setExpanded] = useState<number | null>(null);

  // Filter state (type, difficulty, free-text search).
  const [fType, setFType] = useState('');
  const [fDiff, setFDiff] = useState('');
  const [fSearch, setFSearch] = useState('');

  // AI question-generation form state.
  const [showGen, setShowGen] = useState(false);
  const [genConcept, setGenConcept] = useState('');
  const [genType, setGenType] = useState<QuestionType>('single_choice');
  const [genCount, setGenCount] = useState(5);
  const [genDiff, setGenDiff] = useState('Medium');
  const [generating, setGenerating] = useState(false);
  const [importing, setImporting] = useState(false);

  // CLO tagging - which Course Learning Outcome each question assesses, so an
  // exam built from these questions feeds CLO/PLO attainment when graded (see
  // app/exams/routes.py submit_exam_attempt). Loaded from the course's own
  // catalog subject, same as ContentGeneration's "Link to CLO" dropdown.
  const [clos, setClos] = useState<CLO[]>([]);
  const [savingCloFor, setSavingCloFor] = useState<number | null>(null);

  // Load questions and the available question types in parallel (types fall back to an empty list on failure).
  const load = async () => {
    setLoading(true);
    try {
      const [q, t] = await Promise.all([
        questionBankService.list(courseId),
        questionBankService.types(courseId).catch(() => []),
      ]);
      setQuestions(q);
      setTypes(t);
    } catch (err) {
      setError(apiErrorMessage(err, 'Could not load the question bank.'));
    } finally {
      setLoading(false);
    }
  };

  // On mount / course change: load questions, then concepts and generated sets (for generating/importing) and the course's CLOs via its catalog id.
  useEffect(() => {
    load();
    contentGenerationService.listConcepts(courseId).then(setConcepts).catch(() => {});
    contentGenerationService.list(courseId).then(setSets).catch(() => {});
    courseService.getDetails(courseId)
      .then((c: any) => c?.catalog_id && outcomesService.listCLOs(c.catalog_id))
      .then((c) => setClos(c || []))
      .catch(() => setClos([]));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [courseId]);

  // Save or clear the CLO tag of one question and update it in the list.
  const handleSetClo = async (q: BankQuestion, cloId: string) => {
    setSavingCloFor(q.id);
    try {
      const updated = await questionBankService.update(courseId, q.id,
        cloId ? { clo_id: Number(cloId) } : { clear_clo: true });
      setQuestions((prev) => prev.map((x) => (x.id === q.id ? updated : x)));
    } catch (err) {
      setError(apiErrorMessage(err, "Could not update this question's CLO link."));
    } finally {
      setSavingCloFor(null);
    }
  };

  // Teacher sign-off on an AI-generated question: only Approved items reach
  // practice tests and exams.
  const handleApprove = async (q: BankQuestion) => {
    try {
      const updated = await questionBankService.update(courseId, q.id, { status: 'Approved' });
      setQuestions((prev) => prev.map((x) => (x.id === q.id ? updated : x)));
    } catch (err) {
      setError(apiErrorMessage(err, 'Could not approve this question.'));
    }
  };

  // Apply the type / difficulty / search filters to the question list.
  const filtered = useMemo(() => {
    const s = fSearch.trim().toLowerCase();
    return questions.filter((q) =>
      // Exam / live-quiz pickers only offer teacher-approved questions.
      (!selectable || q.status === 'Approved') &&
      (!fType || q.question_type === fType) &&
      (!fDiff || q.difficulty === fDiff) &&
      (!s || q.prompt.toLowerCase().includes(s) || (q.concept_name || '').toLowerCase().includes(s))
    );
  }, [questions, fType, fDiff, fSearch, selectable]);

  // Ask the AI to generate questions for the chosen concept/type/count/difficulty and prepend them to the list.
  const handleGenerate = async () => {
    if (!genConcept) return;
    setGenerating(true);
    setError('');
    setNotice('');
    try {
      const created = await questionBankService.generate(courseId, {
        concept_node_id: genConcept, question_type: genType, count: genCount, difficulty: genDiff,
      });
      setQuestions((prev) => [...created, ...prev]);
      setNotice(`Added ${created.length} question(s) to the bank.`);
      setShowGen(false);
    } catch (err) {
      setError(apiErrorMessage(err, 'Could not generate questions.'));
    } finally {
      setGenerating(false);
    }
  };

  // Import all questions from an already approved study set, then reload the bank.
  const handleImport = async (contentId: number) => {
    setImporting(true);
    setError('');
    setNotice('');
    try {
      const res = await questionBankService.importFromContent(courseId, contentId);
      setNotice(res.message);
      await load();
    } catch (err) {
      setError(apiErrorMessage(err, 'Could not import that set.'));
    } finally {
      setImporting(false);
    }
  };

  // Delete a question from the bank after confirmation.
  const handleDelete = async (q: BankQuestion) => {
    if (!window.confirm('Remove this question from the bank?')) return;
    try {
      await questionBankService.remove(courseId, q.id);
      setQuestions((prev) => prev.filter((x) => x.id !== q.id));
    } catch (err) {
      setError(apiErrorMessage(err, 'Could not remove this question.'));
    }
  };

  // Generated sets that can be imported (study guides have no questions).
  const importable = sets.filter((s) => s.content_type !== 'study_guide');

  // Render: messages, then (manager mode only) the generate and import panels, then filters and the expandable question list.
  return (
    <div className="space-y-4">
      {error && (
        <div className="bg-red-50 border border-red-200 text-red-600 dark:bg-red-500/10 dark:border-red-500/30 dark:text-red-400 rounded-xl p-4 flex items-start gap-3 text-sm animate-fade-in">
          <AlertTriangle className="w-4 h-4 mt-0.5 shrink-0" />
          {error}
        </div>
      )}
      {notice && (
        <div className="bg-primary-muted border border-primary/20 text-primary rounded-xl p-4 text-sm animate-fade-in flex items-start gap-2">
          <CheckCircle2 className="w-4 h-4 mt-0.5 shrink-0" />
          {notice}
        </div>
      )}

      {!selectable && (
        <div className="glass-panel rounded-2xl p-6 border border-border shadow-card space-y-4">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <h3 className="text-base font-bold text-text-primary flex items-center gap-2">
              <Library className="w-4.5 h-4.5 text-secondary" />
              Question bank
              <span className="text-xs font-semibold text-text-muted">({questions.length})</span>
            </h3>
            <button onClick={() => setShowGen((v) => !v)} className="btn-primary text-xs px-3 py-1.5">
              <Sparkles className="w-3.5 h-3.5" />
              Generate questions
            </button>
          </div>

          {showGen && (
            <div className="border border-border rounded-xl p-4 bg-background space-y-3">
              <div className="grid sm:grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-semibold text-text-secondary mb-1.5">Concept</label>
                  <select className="input-light w-full text-sm" value={genConcept} onChange={(e) => setGenConcept(e.target.value)}>
                    <option value="">Select a concept...</option>
                    {concepts.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-semibold text-text-secondary mb-1.5">Question type</label>
                  <select className="input-light w-full text-sm" value={genType} onChange={(e) => setGenType(e.target.value as QuestionType)}>
                    {(types.length ? types : [{ key: 'single_choice' as QuestionType, label: 'Multiple choice' }]).map((t) => (
                      <option key={t.key} value={t.key}>{t.label}</option>
                    ))}
                  </select>
                </div>
              </div>
              <div className="grid sm:grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-semibold text-text-secondary mb-1.5">How many</label>
                  <input type="number" min={1} max={20} className="input-light w-full text-sm"
                    value={genCount} onChange={(e) => setGenCount(Math.min(20, Math.max(1, parseInt(e.target.value) || 5)))} />
                </div>
                <div>
                  <label className="block text-xs font-semibold text-text-secondary mb-1.5">Difficulty</label>
                  <div className="flex gap-2">
                    {DIFFICULTIES.map((d) => (
                      <button key={d} type="button" onClick={() => setGenDiff(d)}
                        className={`flex-1 rounded-lg border px-2 py-2 text-xs font-bold transition-all ${
                          genDiff === d ? 'border-primary/40 bg-primary-muted text-primary'
                                        : 'border-border bg-surface text-text-secondary'}`}>
                        {d}
                      </button>
                    ))}
                  </div>
                </div>
              </div>
              <div className="flex justify-end gap-2">
                <button onClick={() => setShowGen(false)} className="btn-ghost text-xs px-3 py-1.5">Cancel</button>
                <button onClick={handleGenerate} disabled={generating || !genConcept}
                  className="btn-primary text-xs px-3.5 py-1.5 disabled:opacity-50">
                  {generating ? <RefreshCw className="w-3.5 h-3.5 animate-spin" /> : <Sparkles className="w-3.5 h-3.5" />}
                  {generating ? 'Writing questions...' : 'Generate'}
                </button>
              </div>
            </div>
          )}

          {importable.length > 0 && (
            <div className="border border-border rounded-xl p-3 bg-background">
              <p className="text-xs font-semibold text-text-secondary mb-2 flex items-center gap-1.5">
                <Download className="w-3.5 h-3.5" />
                Import from material you've already approved
              </p>
              <div className="flex flex-wrap gap-2">
                {importable.map((s) => (
                  <button key={s.id} disabled={importing} onClick={() => handleImport(s.id)}
                    className="btn-ghost text-[12px] px-2.5 py-1 disabled:opacity-50">
                    {s.title}
                  </button>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      <div className={selectable ? '' : 'glass-panel rounded-2xl p-6 border border-border shadow-card'}>
        <div className="flex flex-wrap items-center gap-2 mb-4">
          <div className="relative flex-1 min-w-[180px]">
            <Search className="w-3.5 h-3.5 text-text-muted absolute left-3 top-1/2 -translate-y-1/2" />
            <input className="input-light w-full text-xs pl-9" placeholder="Search questions..."
              value={fSearch} onChange={(e) => setFSearch(e.target.value)} />
          </div>
          <Filter className="w-3.5 h-3.5 text-text-muted" />
          <select className="input-light text-xs py-1.5" value={fType} onChange={(e) => setFType(e.target.value)}>
            <option value="">All types</option>
            {types.map((t) => <option key={t.key} value={t.key}>{t.label}</option>)}
          </select>
          <select className="input-light text-xs py-1.5" value={fDiff} onChange={(e) => setFDiff(e.target.value)}>
            <option value="">All levels</option>
            {DIFFICULTIES.map((d) => <option key={d} value={d}>{d}</option>)}
          </select>
        </div>

        {loading ? (
          <div className="text-center py-8 text-sm text-text-muted">Loading...</div>
        ) : filtered.length === 0 ? (
          <div className="text-center py-8 text-text-muted text-sm border-2 border-dashed border-border rounded-xl">
            <EmptyStateIllustration className="w-24 h-24 mx-auto mb-2" />
            {questions.length === 0
              ? 'No questions yet — generate some, or import a set you already approved.'
              : 'No questions match these filters.'}
          </div>
        ) : (
          <div className="space-y-2">
            {filtered.map((q) => {
              const Icon = TYPE_ICONS[q.question_type] || ListChecks;
              const isOpen = expanded === q.id;
              const picked = selectedIds.includes(q.id);
              return (
                <div key={q.id}
                  className={`border rounded-xl p-3 bg-background transition-all ${
                    picked ? 'border-primary/40 bg-primary-muted' : 'border-border'}`}>
                  <div className="flex items-start justify-between gap-3">
                    {selectable && (
                      <input type="checkbox" className="mt-1 shrink-0" checked={picked}
                        onChange={() => onToggleSelect?.(q.id)} />
                    )}
                    <button onClick={() => setExpanded(isOpen ? null : q.id)} className="flex-1 min-w-0 text-left">
                      <p className="text-xs font-semibold text-text-primary flex items-start gap-2">
                        <Icon className="w-3.5 h-3.5 text-secondary shrink-0 mt-0.5" />
                        <span className="min-w-0">{q.prompt}</span>
                      </p>
                      <div className="flex flex-wrap items-center gap-1.5 mt-1.5 ml-5">
                        <span className="text-[11px] font-semibold text-text-muted bg-surface border border-border rounded-full px-2 py-0.5">
                          {q.question_type_label}
                        </span>
                        <span className={badgeClassFor(q.difficulty)}>{q.difficulty}</span>
                        <span className="text-[11px] text-text-muted">{q.points} pt{q.points === 1 ? '' : 's'}</span>
                        {q.status === 'PendingReview' && (
                          <span className="text-[11px] font-semibold rounded-full px-2 py-0.5 border text-amber-600 bg-amber-50 border-amber-200">
                            Pending review
                          </span>
                        )}
                        {q.concept_name && <span className="text-[11px] text-text-muted truncate">· {q.concept_name}</span>}
                        {q.clo_code && (
                          <span className="text-[11px] font-semibold rounded-full px-2 py-0.5 border text-primary bg-primary-muted border-primary/20">
                            {q.clo_code}
                          </span>
                        )}
                      </div>
                    </button>
                    <div className="flex items-center gap-1 shrink-0">
                      <button onClick={() => setExpanded(isOpen ? null : q.id)} className="p-1 text-text-muted hover:text-text-primary rounded">
                        {isOpen ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
                      </button>
                      {!selectable && q.status === 'PendingReview' && (
                        <button onClick={() => handleApprove(q)} className="btn-primary text-[11px] px-2 py-1" title="Approve for students">
                          Approve
                        </button>
                      )}
                      {!selectable && (
                        <button onClick={() => handleDelete(q)} className="p-1 text-text-muted hover:text-rose-500 rounded" title="Remove">
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      )}
                    </div>
                  </div>
                  {isOpen && (
                    <div className="mt-3 ml-5 pt-3 border-t border-border">
                      <AnswerKey question={q} />
                      {q.explanation && <p className="text-[12px] text-text-muted mt-2 italic">{q.explanation}</p>}
                      {!selectable && clos.length > 0 && (
                        <div className="mt-3">
                          <label className="block text-[11px] font-semibold text-text-secondary mb-1">
                            Link to CLO <span className="text-text-muted font-normal">(optional)</span>
                          </label>
                          <select
                            className="input-light text-xs py-1"
                            value={q.clo_id ?? ''}
                            disabled={savingCloFor === q.id}
                            onChange={(e) => handleSetClo(q, e.target.value)}
                          >
                            <option value="">No CLO link</option>
                            {clos.map((c) => (
                              <option key={c.id} value={c.id}>{c.code} — {c.title}</option>
                            ))}
                          </select>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
};

/** Renders the stored answer key for whichever of the five shapes this question uses. */
const AnswerKey: React.FC<{ question: BankQuestion }> = ({ question: q }) => {
  const p = q.payload || {};
  if (q.question_type === 'single_choice' || q.question_type === 'multi_select') {
    const correct = new Set(
      q.question_type === 'single_choice'
        ? [p.correct_index ?? -1]
        : (p.correct_indices || [])
    );
    return (
      <ul className="space-y-1">
        {(p.options || []).map((o, i) => (
          <li key={i} className={`text-[12px] flex items-start gap-1.5 ${
            correct.has(i) ? 'text-emerald-600 dark:text-emerald-400 font-semibold' : 'text-text-secondary'}`}>
            {correct.has(i) ? <CheckCircle2 className="w-3 h-3 mt-0.5 shrink-0" /> : <span className="w-3 shrink-0" />}
            {o}
          </li>
        ))}
      </ul>
    );
  }
  if (q.question_type === 'true_false') {
    return <p className="text-[12px] text-emerald-600 dark:text-emerald-400 font-semibold">Correct: {p.correct ? 'True' : 'False'}</p>;
  }
  if (q.question_type === 'fill_blank') {
    return (
      <p className="text-[12px] text-text-secondary">
        Accepted: <span className="text-emerald-600 dark:text-emerald-400 font-semibold">{(p.accepted || []).join(' / ')}</span>
        {p.case_sensitive && <span className="text-text-muted"> (case sensitive)</span>}
      </p>
    );
  }
  return (
    <ul className="space-y-1">
      {(p.pairs || []).map((pair, i) => (
        <li key={i} className="text-[12px] text-text-secondary">
          <span className="font-semibold text-text-primary">{pair.left}</span>
          <span className="text-text-muted"> → </span>
          <span className="text-emerald-600 dark:text-emerald-400">{pair.right}</span>
        </li>
      ))}
    </ul>
  );
};

export default QuestionBank;
